### ISSUE TITLE
Add Github App to handle code pushing

### ISSUE THREAD

**Issue by vhpx** [vhpx/genie#24]
https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation

**Comment by lluciiiia** [comment]
> Github log in does only verification but not access token to the repo.

- [x] Create an app
- [ ] User needs to install the bot.
- [ ] Bot config (access token) in env variables.
- [ ] Connect (Redirection connection) Genie account & Github Installation (When logging in with Github account, we redirect to the installation then come back)
